EFA_0019_TO_23_TABLES_UPGRADE_PACKAGE
nicmichael/efa pull request #19
Opened 2020-10-31 17:26 UTC by cubitusgh2

Resizable DataList dialogs
-----------------------------------
ItemTypeTable.java
- all tables in the *ListDialog classes now support growing when the dialog is resized to bigger dimensions.

Better readability for all tables
-----------------------------------
Table.java
- add 4 pixels to current font size and use this as the row height

ShowLogbookDialog.java
- add 4 pixels to current font size and use this as the row height
- supports row height changes for nested tables
- No further changes as this would require TableCellRenderer.java to be renamed to avoid conflicts to interface javax.*.TableCellRenderer;

TableCellrenderer.java
- each cell has some whitespace on the left and right side.

BoatDamageList.java
- set minimum widths for date fields so that at least date value is displayed

Bold Table Headers
-----------------------------------
TableHeaderCellRendererBold
- new class

Table.java
- set the bold table header renderer

ShowLogbookDialog.java
- activate new bold table header

Auto tooltip when data does not fit into cell
-----------------------------------
Table.java
- getToolTipText: return Tooltiptext only if data does not fit into cell
- activation of auto tooltips dependent on config setting

ItemTypeTable.java
- activate

EfaConfig.java
- new public property COMMON/Tabellen mit Tooltipps, default true

efa_de.properties
- new item Tabellen_mit_Tooltipps_f\u00fcr_zu_lange_Texte

efa_en.properties
- new item Tabellen_mit_Tooltipps_f\u00fcr_zu_lange_Texte

Alternating Colors
-----------------------------------
Table.java
- alternating colors dependent on config setting
- set inverted selection color

TableCellRenderer.java
- alternating colors dependent on config setting
- alternating colors
- disabled items which are selected get italic font style (disabled text color has bad contrast to inverted selection color)

efa_de.properties
- new item Tabellen_mit_alternierenden_Zeilenfarben

efa_en.properties
- new item Tabellen_mit_alternierenden_Zeilenfarben

2020-11-16 06:00 UTC, nicmichael approved these changes

2020-11-16 06:02 UTC, nicmichael requested changes
LGTM with a small change request to the config options.

2020-11-16 06:02 UTC, nicmichael commented on de/nmichael/efa/core/config/EfaConfig.java
> +            		International.getString("Tabellen mit alternierenden Zeilenfarben")));
I suppose we want users to make use of this feature, right? And there isn't really any downside with it either?

Then I would suggest to make these options "expert" options to not clutter the config dialog with them unless we believe users will frequently want to change them.

2022-04-20 19:10 UTC, cubitusgh2 commented
As requested by nicmichael, new options for tables (alternating row color, tooltipps) moved to "TYPE_EXPERT".

2022-06-04 21:08 UTC, nicmichael approved these changes

2022-06-04 21:08 UTC, merged