Efacloud 241 fixes
nicmichael/efa pull request #222
Opened 2024-11-28 13:35 UTC by tfyh

Fixed 2.4.1 new bug: efa activation / deactivation fails (DataFile & TableBuilder changes) and changes existing behaviour: internet connection failure during authentication triggers retry instead of deactivation
Increased grace periods for settling on program start to 15 seconds (Raspberry Pi scenario) and internet connection unavailability (15 days)

2024-12-29 13:46 UTC, cubitusgh2 submitted a review, later dismissed

2024-12-29 14:02 UTC, cubitusgh2 commented on de/nmichael/efa/data/storage/DataFile.java
> +                if (Daten.project.getProjectStorageType() == IDataAccess.TYPE_EFA_CLOUD)
Check for Daten.project != null has been discarded. Why?
Very often, Daten.project CAN actually be null:
- directly after installing efa with no project open
- closing projects during restores with config data
- closing / reopening projects when loading a diffrent project
I suggest to re-introduce the check to daten.project != null.

2024-12-29 14:08 UTC, cubitusgh2 commented on de/nmichael/efa/data/storage/DataFile.java
> +            if (TableBuilder.tablenames.contains(fName))
this only works if 
- fName does not contain a path
- Also, fName does not contain uppercase letters.
  - Suggestion:   String fName = filename.substring(filename.lastIndexOf('.') + 1).toLower();

2024-12-29 14:24 UTC, cubitusgh2 commented on de/nmichael/efa/data/efacloud/TableBuilder.java
> +    public static final ArrayList<String> tablenames = new ArrayList<>();
Arraylist has a very poor performance when it comes to searching.
This should be converted into an HashTable <String>.

2024-12-29 14:26 UTC, cubitusgh2 requested changes
I suggest some changes.

2025-01-02 18:51 UTC, tfyh commented on de/nmichael/efa/data/efacloud/TableBuilder.java
> +    public static final ArrayList<String> tablenames = new ArrayList<>();
You may do so. 16 entries to be searched on each user action doesn't look like exaggerated performance monger.

2025-01-02 18:57 UTC, tfyh commented on de/nmichael/efa/data/storage/DataFile.java
> +            if (TableBuilder.tablenames.contains(fName))
filename.substring(filename.lastIndexOf('.') + 1) looks for the last dot in the path and takes the part after the dot. That works aso for a pth (actually fileName always contains a path). a conversion to lower is not needed, there is not relevant upper case extension.

2025-01-02 19:06 UTC, tfyh commented on de/nmichael/efa/data/storage/DataFile.java
> +                if (Daten.project.getProjectStorageType() == IDataAccess.TYPE_EFA_CLOUD)
ok, I'm going to provide a pull request

2025-01-02 19:07 UTC, tfyh commented on de/nmichael/efa/data/efacloud/TableBuilder.java
> +    public static final ArrayList<String> tablenames = new ArrayList<>();
PS: it only affects efaCloud users.

2025-01-02 19:18 UTC, tfyh commented
I managed to address with commit c79a317 the same problem as you did, therefor the pull request is no more able to merge. If possible, just drop that commit. I hav no idea how to remove it from the list.

2025-01-04 15:25 UTC, merged