Ready for merge
nicmichael/efa pull request #25
Opened 2021-01-01 19:08 UTC by tfyh

Hallo Nick,
ein gutes neues Jahr wünsche ich! Für mich fängt es ruhig an. Und mit einer neuien Version efacloud.
das sollte nun der Stand sein, der geeignet ist, wieder in den Haupt-Branch zurück-gemerged zu werden. Alles Sprachlevel Java 6, einige Fehler behoben und insbesondere deutlich mehr Logging und Monitoring. Mir sagt github "Able to merge". Würde mich freuen. Dann kann ich für uzukünftige Fehlerbehebungen einen neuen Zweig aufmachen, oder?
Viele Grüße
Martin

2021-01-02 06:30 UTC, nicmichael requested changes
@tfyh Hallo Martin, Dir ebenfalls ein frohes neues Jahr!

Dein PR enthaelt etliche Formatierungsaenderungen, die es schwer machen, die eigentlichen Aenderungen zu reviewen. Ich habe das an einigen Stellen kommentiert, aber nicht ueberall. Bitte ueberarbeite Deinen PR, indem Du diese Formatierungsaenderungen rueckgaengig machst (git hat diverse Kommandos, ein File auf ein frueheres commit/branch zurueckzusetzen). Mit "git diff" (oder "git diff upstream/master", fuer "upstream" == eine Referenz auf meine Repo) kannst Du lokal Aenderungen reviewen bevor Du den PR stellst um sicherzustellen, dass Dein PR nur relevante Aenderungen enthaelt (auf github geht das auch).

Es gibt auch einige Dateien, die Du per .gitignore ausschliessen solltest, damit sie nicht auf github hochgelanden werden.

Wenn Du die Aenderungen lokal vorgenommen hast, kannst Du den PR per commit und push updaten (sobald Dein neues commit im existierenden branch gepushed ist, aktualisiert es den PR automatisch). Dann werde ich den geanderten PR erneut reviewen.

2021-01-02 06:30 UTC, nicmichael commented on .idea/.gitignore
> +# Default ignored files
@tfyh Your files in the .idea directory shouldn't be pushed to github. Please add a ".gitignore" file in the main directory and exlcude ".idea/" in it. Please commit the .gitignore file (push it with your PR) and make sure that none of your .idea files are part of this PR.

2021-01-02 06:30 UTC, nicmichael commented on de/nmichael/efa/data/storage/DataAccess.java
> + * Website:      http://efa.nmichael.de/ License:      GNU General Public License v2
@tfyh Please remove these two obsolete lines.

2021-01-02 06:30 UTC, nicmichael commented on de/nmichael/efa/data/storage/DataAccess.java
> +    protected final LinkedHashMap<String, Integer> fieldTypes = new LinkedHashMap<String, Integer>();
@tfyh Nit: Not that important, but please locally check your changes ("git diff") to make sure what you're pushing is only real changes. Please avoid making formatting changes to existing code to make it easier to review the code. Ideally you'd notice those accidental formatting changes locally and revert them before pushing your code.

2021-01-02 06:30 UTC, nicmichael commented on de/nmichael/efa/data/storage/DataAccess.java
> +                                               String storageObjectDescription) {
Just a formatting change

2021-01-02 06:30 UTC, nicmichael commented on de/nmichael/efa/data/storage/DataAccess.java
> +        switch (type) {
Formatting change.

2021-01-02 06:30 UTC, nicmichael commented on de/nmichael/efa/data/storage/DataAccess.java
> +                        storageObjectDescription);
Formatting change
(and many more below)

2021-01-02 06:30 UTC, nicmichael commented on de/nmichael/efa/data/storage/DataFile.java
> +    private final HashMap<DataKey, DataRecord> data = new HashMap<DataKey, DataRecord>();
@tfyh See above. Please revert formatting changes.

2021-01-02 06:30 UTC, nicmichael commented on de/nmichael/efa/data/storage/IDataAccess.java
> + * License:      GNU General License v2
@tfyh Please revert.

2021-01-02 06:30 UTC, nicmichael commented on de/nmichael/efa/data/storage/IDataAccess.java
> +    int TYPE_EFA_CLOUD = 3;
@tfyh I suppose those changes (and similar below) are by accident? I don't think we ever want to mutate these values... Please revert.

2021-01-02 06:30 UTC, nicmichael commented on de/nmichael/efa/data/storage/IDataAccess.java
> +    boolean isValidAny(DataKey key) throws EfaException;
@tfyh There's lots of changes with this pattern. I agree that maybe "public" isn't necessary here, and the javadoc comment should say EfaException. Could it be that your Idea IDE automatically reformats classes you touch? Is this something you can disable? While some of these changes may be good, they have nothing to do with the efaCloud changes and make it hard to find the real changes when reviewing the code.

2021-01-02 06:30 UTC, nicmichael commented on de/nmichael/efa/gui/EfaBaseFrame.java
> +    // erstellt wird)
@tfyh Too many formatting changes to review the actual changes. Please revert formatting changes.

2021-01-02 06:30 UTC, nicmichael commented on efa_2020_10_04.iml
> +<?xml version="1.0" encoding="UTF-8"?>
What is this file? Please add to or don't add to your commit.

2021-01-03 21:13 UTC, tfyh commented
Hallo Nick,

danke für das Feedback!

Ich habe tatsächlich wohl eine Menge Änderungen erzeugt durch automatische Formatierung in INtellij IDEA. Ich nutze das gerne um den Überblick zu behalten. Das versteckt dann die immer nur marginalen Änderungen in den Dateien aus den Basispaket:
de/nmichael/efa/data/storage/DataAccess.java
de/nmichael/efa/data/storage/DataFile.java
de/nmichael/efa/data/storage/DataRecord.java
de/nmichael/efa/data/storage/EfaCloudStorage.java
de/nmichael/efa/data/storage/IDataAccess.java
de/nmichael/efa/data/storage/MetaData.java
de/nmichael/efa/gui/BaseDialog.java
de/nmichael/efa/gui/EfaBaseFrame.java
de/nmichael/efa/gui/EfaBoathouseFrame.java
de/nmichael/efa/gui/EfaCloudConfigDialog.java
de/nmichael/efa/gui/EfaCloudSynchDialog.java
de/nmichael/efa/gui/util/EfaMenuButton.java 
Ich bekomme das wieder sauber gezogen, wird aber morgen oder übermnorgen werden. Ich melde mich mit einem neuen Pull Request.

Für die Dateien aus dem efacloud Core sind es tatsächlich eine größere Menge an Änderungen und da würde ich erst jetzt von einem halbwegs stabilen Stand ausgehen. Ich hoffe, das ist so ok. Seit heute läuft es im Bootshaus und ich habe noch mit Timing-Probleen zu kämpfen, weil die Internet-Anbindung dort eher schlecht ist.

Viele Grüße
Martin

2021-01-04 21:16 UTC, tfyh commented
Hallo Nick,
die Umformatierungen habe ich zurück bekommen, den .idea-Ordner bekomme ich nicht heraus. Ich habe es einfach bis jetzt noch nicht geschafft, mich per command line in git sauber in das repo zuverbinden und jetzt muss ich och ein paar Korrekturen machen, weil ich morgen im Bootshaus aktualkisieren gehe.

2021-01-05 23:36 UTC, nicmichael commented on de/nmichael/efa/gui/EfaCloudConfigDialog.java
> +                .getMessage("Efacloud Server Kommunikation steuern.\nAktueller Status: {state}", queueState) + "\n";
Internationalisierte Strings duerfen keine \n enthalten. Bitte brich den String in zwei separate getString/getMessage calls.
Achte bitte auch auf einheitliche Schreibweise von "efaCloud". Ich schreibe efa immer - auch am Satzanfang - mit kleinem "e". efaCloud sollte also immer "efaCloud" geschrieben werden.

2021-01-05 23:36 UTC, nicmichael commented on de/nmichael/efa/gui/EfaCloudConfigDialog.java
> +        category = "%01%" + International.getString("Efacloud Optionen");
"efaCloud"

2021-01-05 23:37 UTC, nicmichael commented on de/nmichael/efa/gui/EfaCloudConfigDialog.java
> +                            International.getString(International.getString("Efacloud feature deaktivieren"))));
"efaCloud"

2021-01-08 21:08 UTC, tfyh commented
Hallo Nick,

ich habe jetzt erst einmal versucht, das Repository zu bereinigen. Diesmal scheint es geklappt zu haben. Die Schwierigkeit war, dass ich es aus der IDEA-GUI heraus aufgebaut habe und jetzt mich irgendwie auf der Kommandzeile verbinden musste. Da scheitert man im ersten Schritt an ganz einfachen Dingen. Jetzt habe ich den Commit + Push aber auf der Kommandozeitle abgesetzt bekommen. 

Das ist nun natürlich wieder ein neuer Stand. efaCloud läuft im Bootshaus und da lernt man eine Menge. Zum Beispiel, dass der Raspberry mit einer Systemzeit vom 14.2.2019 11:12h beginnt, dann irgendwann sich fängt und dabei die Schnittstelle zum Server neu initialisiert, die dann doppelt ausgeprägt ist - die alte wird nicht geschlossen. Hatte ich bei einer Singleton Klasse bisher noch nie und es hat mich mächtig Kraft gekostet, das herauszufinden. Jetzt hängt die Schnittstelle am Project Objekt, das scheint besser zu funktionieren. Ich habe entsprechend eine Menge bei Logging und Monitoring geändert.

Ich habe nicht erwartet, dass da immer noch so viele Formatänderungen drin sind. Die Ursache dafür ist mir jetzt klar: Ich habe die Bereinigung durchgeführt durch Kopie aus dem Master (kompletter Quelltext) und erneutes Hinzufügen der Änderungen. Aber die IDEA GUI löscht schon beim Texteinfügen instantan trailing spaces und korrigiert manche Einrückungen - teilweise sogar beim Speichern. Und das habe ich nicht gemerkt. Jetzt habe ich es manuell zurückgesetzt. Weil es aber auch beim Speichern passiert, bin ich nicht alle Änderungen losgeworden, aber die meisten wohl schon.

Ich würde mich freuen, wenn wir jetzt mergen könnten. Dann kann ich auf der aktuellen Version aufsetzen und die Kameraden im Verein warten schon darauf. Ich glaube auch nicht, dass ich an den Dateien, die nicht explizit efaCloud sind, noch viele Änderungen habe. Dieses Durcheinander wird sich nicht wiederholen.

Viele Grüße
Martin

2021-01-08 22:19 UTC, nicmichael commented
Hallo @tfyh, jetzt sind die .idea und iml files weg, dafuer aber ploetzlich alle files in root/ sowie LICENSE und COPYING ploetzlich geaendert. Auch Project.java und SimpleFilePrinter.java (letzteres hast Du vermutlich gar nicht angefasst) sind stark veraendert. Ich weiss nicht, wie das passiert ist, aber so kann ich das nicht mergen. Ich werde versuchen, das zu bereinigen.

2021-01-08 23:51 UTC, nicmichael commented
Hallo @tfyh, ich habe Dir eine email geschrieben. Dein bereinigter branch ist jetzt hier: https://github.com/nicmichael/efa/tree/efacloud_cleanup

2021-01-09 23:06 UTC, nicmichael commented
This PR has become obsolete with https://github.com/nicmichael/efa/pull/26.

2021-01-09 23:06 UTC, closed without merging