Hallo Nick,
nicmichael/efa pull request #27
Opened 2021-01-23 20:30 UTC by tfyh

Nach zwei weiteren Wochen Pilotbetrieb nun eine etwas stabilere Version. Die läuft seit etwa einer Woche ganz gut durch. Folgende Änderungen:
Im package cli Klasse CLI ein neues Menü efacloud, um die Upload-Synchronisation als automatischen Ablauf starten zu können, ferner einen Menüeintrag in MenuMain und eine neue Klasse MenuEfaCloud, die davon angesprochen wird.
Im ProjectRecord einen Getter getEfaCloudURL() hinzugefügt
Im Project eine Änderung durch de Umbenamung des Beendens der Queue in "cancel()" statt "terminate()"
In EfaBaseFrame eine Referenz zur Variable boatStatus durch die Referenz zum Getter getBoatStatus() ersetzt. Das war erforderlich, um den Bootssatus bei Booten auf Wasser ändern zu können, was wiederum erforderlich ist, wenn die Fahrtennummer korrigiert werden muss, weil die Fahrt sonst doppelt vergeben wäre.
Im EfaCloudConfigDialog die Möglichkeit ergänzt, aus dem Status DISCONECTED heraus efaCloud zu deaktivieren.
Im InternetAccessManager die Statistikerstellung verbessert
Eine Menge Änderungen wegen durchgängiger Formalisierung der Transaktionen in ein enum, statt String-Referenzen. Zum Beispiel im TableBuilder nur solche Anpassungen.
In der Klasse Transaktionen Änpassungen beim Logging
In den Klassen TxRequestQueue, SynchControl und TxResponseHandler deutliche Überarbeitung aufgrund verschiedener Fehlerszenarien. Hier sind auch Formatierungsänderungen drin, weil es noch so viel Bewegung gab, habe ich das gelassen.
Martin

2021-01-24 23:07 UTC, nicmichael requested changes
Danke @tfyh. Nur ein ganz kleiner Aenderungswunsch, sonst ist alles gut.
Vielen Dank fuer den gut dokumentierten und "sauberen" PR!

2021-01-24 23:07 UTC, nicmichael commented on de/nmichael/efa/cli/MenuMain.java
> +                        !cli.getAdminRecord().isAllowedRestoreBackup()) {
Ich hatte beim Merge Deines ersten PRs die Permissions fuer efaCloud geaendert. Statt Backup/Restore braucht ein Admin isAllowedAdministerProjectLogbook(). Bitte ersetze diese beiden Zeilen gegen isAllowedAdministerProjectLogbook().

2021-01-25 18:48 UTC, tfyh commented on de/nmichael/efa/cli/MenuMain.java
> +                        !cli.getAdminRecord().isAllowedRestoreBackup()) {
Habe ich jetzt gemacht.

2021-01-25 23:23 UTC, nicmichael approved these changes
LGTM

2021-01-25 23:24 UTC, merged